const ListBilling = {
  data: [
    {
      ReceiptCode: 21500,
      Name: "Kế toán đại cương",
      NumberOfCredits: 4,
      StatusRegistration: "Đăng ký mới",
      Amount: "1.600.000",
      Submitted: "1.600.000",
      Deduct: "",
      Debts: "",
      status: true,
    },
    {
      ReceiptCode: 2150,
      Name: "Nguyên lý kế toán",
      NumberOfCredits: 2,
      StatusRegistration: "Đăng ký mới",
      Amount: "2.000.000",
      Submitted: "2.000.000",
      Deduct: "",
      Debts: "",
      status: true,
    },
    {
      ReceiptCode: 2151,
      Name: "Kế toán tài chính doanh nghiệp 1",
      NumberOfCredits: 3,
      StatusRegistration: "Đăng ký mới",
      Amount: "1.600.000",
      Submitted: "",
      Deduct: "800.000",
      Debts: "800.000",
      status: false,
    },
    {
      ReceiptCode: 2152,
      Name: "Kế toán tài chính doanh nghiệp 2",
      NumberOfCredits: 2,
      StatusRegistration: "Đăng ký mới",
      Amount: "3.000.000",
      Submitted: "",
      Deduct: "",
      Debts: "3.000.000",
      status: false,
    },
    {
      ReceiptCode: 2153,
      Name: "Kế toán quản trị",
      NumberOfCredits: 3,
      StatusRegistration: "Đăng ký mới",
      Amount: "1.600.000",
      Submitted: "",
      Deduct: "",
      Debts: "1.600.000",
      status: false,
    },
    {
      ReceiptCode: 2154,
      Name: "Bảo hiểm Y tế bắt buộc ",
      NumberOfCredits: 4,
      StatusRegistration: "Đăng ký mới",
      Amount: "1.600.000",
      Submitted: "1.600.000",
      Deduct: "",
      Debts: "",
      status: true,
    },
    {
      ReceiptCode: 2155,
      Name: "Chủ nghĩa Mác - Lê-nin",
      NumberOfCredits: 1,
      StatusRegistration: "Đăng ký mới",
      Amount: "2.000.000",
      Submitted: "2.000.000",
      Deduct: "",
      Debts: "",
      status: true,
    },
  ],
};

export default ListBilling;
